import type { Metadata } from 'next';
import './globals.css';

// const inter = Inter({ subsets: ['latin'] });
import { cn } from '@/lib/utils'; // fn helper to join classnames and use conditional classes
import { Inter as FontSans } from 'next/font/google';

// // Toaster
import { Toaster } from '@/components/ui/toaster';

// // Sonner
import { Toaster as SonnerToaster } from '@/components/ui/sonner';

// // ThemeProvider
import { ThemeProvider } from '@/components/ui/theme-provider';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          fontSans.variable
        )}
      >
        {/* only wrap children */}
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>

        <Toaster />
        <SonnerToaster
          // to set custom colors xq es stayless x default
          richColors
        />
      </body>
    </html>
  );
}
